-- Hand edits to the generated SQL (draft orders spec section 2.3):
-- 1. D1 runs a migration inside a transaction, where foreign key
--    enforcement cannot be switched off, so the rebuild defers foreign key
--    checks to the commit instead (defer_foreign_keys, as D1 documents). No table
--    references orders by foreign key (events.order_id and
--    purchase_orders.order_id are plain text), and orders' own reference to
--    workspaces holds for every copied row.
-- 2. The copy names only the eleven columns orders has before this
--    migration. drizzle-kit listed the four new draft columns in the SELECT
--    too, which fails ("no such column") or, where SQLite accepts
--    double-quoted strings, copies the column names as text into every row.
PRAGMA defer_foreign_keys = on;--> statement-breakpoint
CREATE TABLE `__new_orders` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`shopify_order_id` text,
	`name` text NOT NULL,
	`shopify` text NOT NULL,
	`status_key` text NOT NULL,
	`status_set_by` text,
	`status_set_at` integer,
	`created_at` integer NOT NULL,
	`synced_at` integer NOT NULL,
	`notified_at` integer,
	`shopify_draft_id` text,
	`draft_name` text,
	`draft_snapshot` text,
	`draft_deleted_at` integer,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "order_source" CHECK(shopify_order_id is not null or shopify_draft_id is not null)
);
--> statement-breakpoint
INSERT INTO `__new_orders`("id", "workspace_id", "shopify_order_id", "name", "shopify", "status_key", "status_set_by", "status_set_at", "created_at", "synced_at", "notified_at") SELECT "id", "workspace_id", "shopify_order_id", "name", "shopify", "status_key", "status_set_by", "status_set_at", "created_at", "synced_at", "notified_at" FROM `orders`;--> statement-breakpoint
DROP TABLE `orders`;--> statement-breakpoint
ALTER TABLE `__new_orders` RENAME TO `orders`;--> statement-breakpoint
PRAGMA defer_foreign_keys = off;--> statement-breakpoint
CREATE UNIQUE INDEX `order_unique` ON `orders` (`workspace_id`,`shopify_order_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `order_draft_unique` ON `orders` (`workspace_id`,`shopify_draft_id`);--> statement-breakpoint
CREATE INDEX `order_ws_created` ON `orders` (`workspace_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `order_ws_status` ON `orders` (`workspace_id`,`status_key`);--> statement-breakpoint
CREATE INDEX `order_open_drafts` ON `orders` (`workspace_id`,`created_at`) WHERE shopify_order_id is null;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `draft_sync_cursor` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `draft_sync_cursor_since` integer;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `draft_last_sync_at` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `draft_checked_at` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
-- Data steps (hand-written, not generated by drizzle-kit). Approved becomes
-- the status Approve uses, in each workspace that has no draft_completed
-- link yet.
UPDATE `statuses` SET `shopify_link` = 'draft_completed'
WHERE `key` = 'approved' AND `shopify_link` IS NULL
  AND NOT EXISTS (SELECT 1 FROM `statuses` s2
                  WHERE s2.`workspace_id` = `statuses`.`workspace_id` AND s2.`shopify_link` = 'draft_completed');--> statement-breakpoint
-- A Rejected status at the end of every workspace that has room (fewer than
-- STATUS_LIST_MAX, 20) and none yet. The id is UUID-shaped like the app's
-- own ids.
INSERT INTO `statuses` (`id`, `workspace_id`, `key`, `label`, `color`, `sort`, `triggers_po`, `shopify_link`)
SELECT lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-'
             || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
       w.`id`, 'rejected', 'Rejected', 'pink',
       COALESCE((SELECT max(s.`sort`) FROM `statuses` s WHERE s.`workspace_id` = w.`id`), -1) + 1,
       0, 'draft_rejected'
FROM `workspaces` w
WHERE NOT EXISTS (SELECT 1 FROM `statuses` s WHERE s.`workspace_id` = w.`id`
                  AND (s.`key` = 'rejected' OR s.`shopify_link` = 'draft_rejected'))
  AND (SELECT count(*) FROM `statuses` s WHERE s.`workspace_id` = w.`id`) < 20;
