CREATE TABLE `locations` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`shopify_location_id` text NOT NULL,
	`company_id` text,
	`name` text NOT NULL,
	`address` text,
	`active` integer DEFAULT true NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `location_shopify_unique` ON `locations` (`workspace_id`,`shopify_location_id`);--> statement-breakpoint
ALTER TABLE `orders` ADD `location_id` text;
--> statement-breakpoint
-- Data step (hand-written, not generated by drizzle-kit; comprehensive
-- design section 2). A Cancelled status at the end of every workspace that
-- has room (fewer than STATUS_LIST_MAX, 20) and no status with the key
-- cancelled or the cancelled link yet, like 0010 added Rejected. Closed
-- (0011), so the Open view leaves cancelled cards out. The id is
-- UUID-shaped like the app's own ids.
INSERT INTO `statuses` (`id`, `workspace_id`, `key`, `label`, `color`, `sort`, `triggers_po`, `shopify_link`, `closed`)
SELECT lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-'
             || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
       w.`id`, 'cancelled', 'Cancelled', 'slate',
       COALESCE((SELECT max(s.`sort`) FROM `statuses` s WHERE s.`workspace_id` = w.`id`), -1) + 1,
       0, 'cancelled', 1
FROM `workspaces` w
WHERE NOT EXISTS (SELECT 1 FROM `statuses` s WHERE s.`workspace_id` = w.`id`
                  AND (s.`key` = 'cancelled' OR s.`shopify_link` = 'cancelled'))
  AND (SELECT count(*) FROM `statuses` s WHERE s.`workspace_id` = w.`id`) < 20;
